on:
    pull_request:
        paths:
            - slides.md

jobs:
    validate:
        runs-on: ubuntu-latest
        concurrency:
            group: ${{ github.ref }}
            cancel-in-progress: true
        steps:
            - uses: actions/checkout@v6
            - uses: pnpm/setup@v2
            - run: pnpm run build --base ${{github.event.repository.name}}
